name: Deploy to Server

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Sync Files to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}
          script: |
            cd /repositories/adm-trisakti
            git pull origin dev
            cp -r SITU-Framework ~/fe-trisakti.amisbudi.cloud 
